name: Publish Docker image
on:
  push:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: mahgeneve/sigidoc_latest
          tags: latest
          dockerfile: Dockerfile
  deploy:
    name: Deploy image
    needs: push_to_registry
    runs-on: self-hosted
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: docker pull ghcr.io/mahgeneve/sigidoc_latest:latest
      - name: Stop previous container
        run: docker stop sigidoc || true && docker rm sigidoc || true
      - name: Run image
        run: docker run -p 9000:9999 -d --rm --name sigidoc ghcr.io/mahgeneve/sigidoc_latest:latest
